"""
I/O and Data Ingestion Module for Single-Cell Analysis Workbench.
Supports loading upstream pipeline matrices (TSV/CSV), 10x Genomics MTX, H5AD,
and exporting for R/Seurat compatibility.
"""

from pathlib import Path
from typing import List, Optional, Union

import anndata as ad
import numpy as np
import pandas as pd
import scipy.sparse as sp
from rich.console import Console

console = Console()


def load_upstream_matrix(
    file_path: Union[str, Path], transpose: bool = True, sparse: bool = True
) -> ad.AnnData:
    """
    Load gene-by-cell count matrix generated by the upstream pipeline.

    Parameters
    ----------
    file_path : str or Path
        Path to gene_cell_count_matrix.tsv or .csv.
    transpose : bool, default True
        If True, transposes matrix from (Genes x Cells) to standard (Cells x Genes) AnnData format.
    sparse : bool, default True
        If True, converts count matrix into scipy CSR sparse matrix for memory efficiency.

    Returns
    -------
    ad.AnnData
        Initial AnnData object with counts in .X and raw counts in .layers['counts'].
    """
    path = Path(file_path)
    if not path.exists():
        raise FileNotFoundError(f"Upstream matrix not found at: {path.resolve()}")

    sep = "\t" if path.suffix in [".tsv", ".txt"] else ","
    console.print(f"[bold cyan]Ingesting upstream matrix:[/bold cyan] {path.name}")

    # Read matrix
    df = pd.read_csv(path, sep=sep, index_col=0)

    return from_dataframe(df, is_genes_by_cells=transpose, sparse=sparse)


def load_10x_directory(dir_path: Union[str, Path]) -> ad.AnnData:
    """Load standard 10x Genomics folder containing matrix.mtx.gz, barcodes.tsv.gz, features.tsv.gz."""
    import scanpy as sc

    p = Path(dir_path)
    if not p.exists():
        raise FileNotFoundError(f"10x directory not found: {p}")
    adata = sc.read_10x_mtx(p, var_names="gene_symbols", cache=False)
    adata.layers["counts"] = adata.X.copy()
    return adata


def save_h5ad(adata: ad.AnnData, output_path: Union[str, Path], compression: str = "gzip"):
    """Save AnnData object to compressed H5AD format."""
    out_p = Path(output_path)
    out_p.parent.mkdir(parents=True, exist_ok=True)
    adata.write_h5ad(out_p, compression=compression)
    console.print(f"[bold green]✔ Saved AnnData to:[/bold green] {out_p}")


def export_for_seurat(
    adata: ad.AnnData, output_dir: Union[str, Path], layer: Optional[str] = "counts"
):
    """
    Export raw/normalized counts and metadata as CSV files for seamless import into R / Seurat.
    Creates:
      - counts.csv (Genes x Cells)
      - metadata.csv (Cells x Metadata)
      - embeddings.csv (UMAP coordinates)
    """
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    # 1. Counts matrix (Genes as rows, Cells as columns)
    if layer is not None and layer not in adata.layers:
        raise KeyError(f"Unknown layer: {layer}")
    X = adata.layers[layer] if layer is not None else adata.X
    if sp.issparse(X):
        X = X.toarray()
    df_counts = pd.DataFrame(X.T, index=adata.var_names, columns=adata.obs_names)
    df_counts.to_csv(out_dir / "counts.csv")

    # 2. Metadata
    adata.obs.to_csv(out_dir / "metadata.csv")

    # 3. UMAP coordinates if present
    if "X_umap" in adata.obsm:
        df_umap = pd.DataFrame(
            adata.obsm["X_umap"], index=adata.obs_names, columns=["UMAP_1", "UMAP_2"]
        )
        df_umap.to_csv(out_dir / "embeddings_umap.csv")

    console.print(f"[bold green]✔ Exported Seurat files to:[/bold green] {out_dir}")


def from_dataframe(
    df: pd.DataFrame,
    obs: Optional[pd.DataFrame] = None,
    var: Optional[pd.DataFrame] = None,
    is_genes_by_cells: bool = False,
    sparse: bool = True,
) -> ad.AnnData:
    """
    Construct an AnnData object directly from a Pandas DataFrame.

    Parameters
    ----------
    df : pd.DataFrame
        Expression count or normalized matrix.
    obs : pd.DataFrame, optional
        Cell metadata. If None, created with index matching cell IDs.
    var : pd.DataFrame, optional
        Gene metadata. If None, created with index matching gene symbols.
    is_genes_by_cells : bool, default False
        If True, transposes matrix from (Genes x Cells) to (Cells x Genes).
    sparse : bool, default True
        If True, stores expression matrix as scipy.sparse.csr_matrix.
    """
    if is_genes_by_cells:
        mat_df = df.T
    else:
        mat_df = df

    if mat_df.empty:
        raise ValueError("Expression matrix must contain cells and genes")
    values = mat_df.to_numpy(dtype=np.float64)
    if not np.isfinite(values).all() or (values < 0).any():
        raise ValueError("Expression must contain finite nonnegative values")
    cell_ids = mat_df.index.astype(str).tolist()
    gene_ids = mat_df.columns.astype(str).tolist()

    if len(set(cell_ids)) != len(cell_ids) or len(set(gene_ids)) != len(gene_ids):
        raise ValueError("Cell and gene identifiers must be unique")
    if sparse:
        X = sp.csr_matrix(mat_df.values, dtype=np.float32)
    else:
        X = np.array(mat_df.values, dtype=np.float32)

    cell_obs = _align_metadata(obs, cell_ids) if obs is not None else pd.DataFrame(index=cell_ids)
    gene_var = _align_metadata(var, gene_ids) if var is not None else pd.DataFrame(index=gene_ids)

    if "gene_name" not in gene_var.columns:
        gene_var["gene_name"] = gene_ids

    adata = ad.AnnData(X=X, obs=cell_obs, var=gene_var)
    adata.layers["counts"] = adata.X.copy()
    console.print(
        f"[bold green]✔ Ingested DataFrame:[/bold green] {adata.n_obs} cells × {adata.n_vars} genes"
    )
    return adata


def from_numpy(
    X: Union[np.ndarray, sp.spmatrix],
    cell_names: Optional[List[str]] = None,
    gene_names: Optional[List[str]] = None,
    obs: Optional[pd.DataFrame] = None,
    var: Optional[pd.DataFrame] = None,
    sparse: bool = True,
) -> ad.AnnData:
    """
    Construct an AnnData object directly from a NumPy array or SciPy sparse matrix.

    Parameters
    ----------
    X : np.ndarray or sp.spmatrix
        2D matrix of shape (n_cells, n_genes).
    cell_names : list of str, optional
        Cell identifiers. If None, generated as cell_0, cell_1, ...
    gene_names : list of str, optional
        Gene identifiers. If None, generated as gene_0, gene_1, ...
    obs : pd.DataFrame, optional
        Cell metadata table.
    var : pd.DataFrame, optional
        Gene metadata table.
    sparse : bool, default True
        Convert to CSR sparse matrix if not already sparse.
    """
    if len(X.shape) != 2 or min(X.shape) == 0:
        raise ValueError("Expected a nonempty cells-by-genes matrix")
    values = X.data if sp.issparse(X) else np.asarray(X)
    if not np.isfinite(values).all() or (values < 0).any():
        raise ValueError("Expression must contain finite nonnegative values")
    n_cells, n_genes = X.shape

    if cell_names is None:
        cell_names = [f"cell_{i}" for i in range(n_cells)]
    if gene_names is None:
        gene_names = [f"gene_{j}" for j in range(n_genes)]

    cell_names = list(map(str, cell_names))
    gene_names = list(map(str, gene_names))
    if len(cell_names) != n_cells or len(gene_names) != n_genes:
        raise ValueError("Identifier lengths must match matrix shape")
    if len(set(cell_names)) != n_cells or len(set(gene_names)) != n_genes:
        raise ValueError("Cell and gene identifiers must be unique")
    if sparse and not sp.issparse(X):
        X_mat = sp.csr_matrix(X, dtype=np.float32)
    elif not sparse and sp.issparse(X):
        X_mat = X.toarray()
    else:
        X_mat = X.astype(np.float32) if hasattr(X, "astype") else X

    cell_obs = (
        _align_metadata(obs, cell_names) if obs is not None else pd.DataFrame(index=cell_names)
    )
    gene_var = (
        _align_metadata(var, gene_names) if var is not None else pd.DataFrame(index=gene_names)
    )
    if "gene_name" not in gene_var.columns:
        gene_var["gene_name"] = gene_names

    adata = ad.AnnData(X=X_mat, obs=cell_obs, var=gene_var)
    adata.layers["counts"] = adata.X.copy()
    console.print(
        f"[bold green]✔ Ingested NumPy/SciPy matrix:[/bold green] {adata.n_obs} cells × {adata.n_vars} genes"
    )
    return adata


def to_dataframe(
    adata: ad.AnnData, layer: Optional[str] = None, use_raw: bool = False
) -> pd.DataFrame:
    """
    Export expression matrix from AnnData to a Pandas DataFrame (Cells as rows, Genes as columns).

    Parameters
    ----------
    adata : ad.AnnData
        Annotated single-cell dataset.
    layer : str, optional
        Layer to extract (e.g. 'counts', 'scaled', 'normalized'). If None, extracts .X.
    use_raw : bool, default False
        If True and adata.raw exists, extracts data from adata.raw.
    """
    if use_raw and layer is not None:
        raise ValueError("Choose either use_raw or layer")
    if use_raw and adata.raw is None:
        raise ValueError("AnnData.raw is not available")
    if layer is not None and layer not in adata.layers:
        raise KeyError(f"Unknown layer: {layer}")
    if use_raw and adata.raw is not None:
        X = adata.raw.X
        var_names = adata.raw.var_names
    elif layer and layer in adata.layers:
        X = adata.layers[layer]
        var_names = adata.var_names
    else:
        X = adata.X
        var_names = adata.var_names

    if sp.issparse(X):
        X = X.toarray()

    return pd.DataFrame(X, index=adata.obs_names, columns=var_names)


def to_numpy(adata: ad.AnnData, layer: Optional[str] = None, use_raw: bool = False) -> np.ndarray:
    """
    Export expression matrix from AnnData to a dense 2D NumPy array.
    """
    if use_raw and layer is not None:
        raise ValueError("Choose either use_raw or layer")
    if use_raw and adata.raw is None:
        raise ValueError("AnnData.raw is not available")
    if layer is not None and layer not in adata.layers:
        raise KeyError(f"Unknown layer: {layer}")
    if use_raw and adata.raw is not None:
        X = adata.raw.X
    elif layer and layer in adata.layers:
        X = adata.layers[layer]
    else:
        X = adata.X

    if sp.issparse(X):
        return X.toarray()
    return np.array(X)


def get_embedding_df(
    adata: ad.AnnData, embedding_key: str = "X_umap", col_prefix: Optional[str] = None
) -> pd.DataFrame:
    """
    Extract low-dimensional embedding (e.g., PCA, UMAP, t-SNE) as a Pandas DataFrame.
    """
    if embedding_key not in adata.obsm:
        raise KeyError(f"Embedding key '{embedding_key}' not found in adata.obsm!")

    mat = adata.obsm[embedding_key]
    n_dim = mat.shape[1]

    if col_prefix is None:
        col_prefix = embedding_key.replace("X_", "").upper()

    cols = [f"{col_prefix}_{i + 1}" for i in range(n_dim)]
    return pd.DataFrame(mat, index=adata.obs_names, columns=cols)


def _align_metadata(frame, names):
    frame = frame.copy()
    frame.index = frame.index.astype(str)
    if not frame.index.is_unique or not pd.Index(names).isin(frame.index).all():
        raise ValueError("Metadata requires unique IDs covering every matrix row/column")
    return frame.loc[names].copy()


def annotate_from_gtf(adata: ad.AnnData, gtf_path: Union[str, Path]) -> ad.AnnData:
    """Attach gene_name/chromosome from the exact GTF used upstream, matching gene_id.

    Unmatched IDs retain their identifier as gene_name. No version suffixes are
    removed. Returns the same AnnData; counts and var_names are unchanged.
    """
    import gzip
    import re

    path = Path(gtf_path)
    opener = gzip.open if path.suffix == ".gz" else open
    annotation = {}
    wanted = set(adata.var_names)
    with opener(path, "rt") as handle:
        for line in handle:
            if line.startswith("#"):
                continue
            fields = line.rstrip("\n").split("\t")
            if len(fields) != 9:
                continue
            attrs = dict(re.findall(r'(\w+)\s+"([^"]*)"', fields[8]))
            gene = attrs.get("gene_id")
            if gene in wanted:
                record = (attrs.get("gene_name", gene), fields[0])
                if gene in annotation and annotation[gene] != record:
                    raise ValueError(f"Conflicting GTF annotations for {gene}")
                annotation[gene] = record
    if not annotation:
        raise ValueError("No gene IDs match the GTF; check reference release and identifier type")
    adata.var["gene_name"] = [annotation.get(g, (g, ""))[0] for g in adata.var_names]
    adata.var["chromosome"] = [annotation.get(g, (g, ""))[1] for g in adata.var_names]
    adata.var["annotation_matched"] = [g in annotation for g in adata.var_names]
    return adata
