"""I/O and Data Ingestion Module for SMART-seq2 Analysis Workbench.

Provides robust loaders for SMART-seq2 gene-by-cell matrices (RSEM, STAR, featureCounts, Kallisto),
paired plate/well metadata tables, H5AD files with backed-mode support (NFR-3), and Seurat export.
Complies with scRNAseq_Workbench_Requirements.md (FR-6, NFR-3, NFR-5).
"""

from pathlib import Path
from typing import Optional, Tuple, Union

import anndata as ad
import numpy as np
import pandas as pd
import scipy.sparse as sp
from rich.console import Console

from workbench_utils.qc import parse_plate_metadata

console = Console()


def load_smartseq2_matrix(
    count_path: Union[str, Path],
    metadata_path: Optional[Union[str, Path]] = None,
    transpose: bool = True,
    sparse: bool = True,
    ercc_prefix: Union[str, Tuple[str, ...]] = ("ERCC-", "ercc-"),
) -> ad.AnnData:
    """Load SMART-seq2 gene-by-cell count matrix with optional plate/well metadata.

    Parameters
    ----------
    count_path : str or Path
        Path to count matrix (TSV, CSV, or TXT).
        Typically rows are genes and columns are single-cell wells (if transpose=True).
    metadata_path : str or Path, optional
        Path to sample/plate metadata CSV/TSV matching well cell IDs.
    transpose : bool, default True
        Set True if input rows are Genes and columns are Cells/Wells (standard SMART-seq2 format).
    sparse : bool, default True
        Store count matrix as scipy CSR sparse matrix to save memory.
    ercc_prefix : tuple of str, default ("ERCC-", "ercc-")
        Prefix to identify synthetic ERCC spike-in controls.

    Returns
    -------
    ad.AnnData
        AnnData with raw counts in .X and .layers['counts'], tagged ERCC in .var['is_ercc'],
        and plate/well coordinates in .obs.
    """
    path = Path(count_path)
    if not path.exists():
        raise FileNotFoundError(f"SMART-seq2 count matrix file not found: {path.resolve()}")

    sep = "\t" if path.suffix in [".tsv", ".txt"] else ","
    console.print(f"[bold cyan]Ingesting SMART-seq2 matrix:[/bold cyan] {path.name}")

    df = pd.read_csv(path, sep=sep, index_col=0)

    if transpose:
        X = df.values.T
        obs_names = [str(c) for c in df.columns]
        var_names = [str(r) for r in df.index]
    else:
        X = df.values
        obs_names = [str(r) for r in df.index]
        var_names = [str(c) for c in df.columns]

    if sparse:
        X = sp.csr_matrix(X, dtype=np.float32)
    else:
        X = np.asarray(X, dtype=np.float32)

    obs = pd.DataFrame(index=obs_names)
    var = pd.DataFrame(index=var_names)
    var["gene_name"] = var_names

    if isinstance(ercc_prefix, str):
        ercc_prefix = (ercc_prefix,)
    var["is_ercc"] = [any(str(g).startswith(p) for p in ercc_prefix) for g in var_names]

    adata = ad.AnnData(X=X, obs=obs, var=var)
    adata.layers["counts"] = adata.X.copy()

    # Automatically parse plate and well coordinates
    parse_plate_metadata(adata)

    # Attach external plate/well metadata if provided
    if metadata_path is not None:
        meta_p = Path(metadata_path)
        if meta_p.exists():
            meta_sep = "\t" if meta_p.suffix in [".tsv", ".txt"] else ","
            meta_df = pd.read_csv(meta_p, sep=meta_sep, index_col=0)
            meta_df.index = meta_df.index.astype(str)
            for col in meta_df.columns:
                adata.obs[col] = meta_df.reindex(adata.obs_names)[col].values
            console.print(f"[bold green]✔ Attached plate metadata:[/bold green] {meta_p.name}")
        else:
            console.print(
                f"[bold yellow]Warning:[/bold yellow] Metadata file not found: {meta_p.resolve()}"
            )

    console.print(
        f"[bold green]✔ SMART-seq2 AnnData created:[/bold green] {adata.n_obs} wells/cells, "
        f"{adata.n_vars} features ({adata.var['is_ercc'].sum()} ERCC spike-ins)."
    )
    return adata


def load_upstream_matrix(
    file_path: Union[str, Path],
    transpose: bool = True,
    sparse: bool = True,
) -> ad.AnnData:
    """Load gene-by-cell count matrix generated by upstream pipelines (TSV/CSV)."""
    return load_smartseq2_matrix(
        count_path=file_path,
        metadata_path=None,
        transpose=transpose,
        sparse=sparse,
    )


def load_h5ad(
    file_path: Union[str, Path],
    backed: Optional[str] = None,
) -> ad.AnnData:
    """Load AnnData from H5AD file, optionally in backed mode for large datasets (NFR-3)."""
    path = Path(file_path)
    if not path.exists():
        raise FileNotFoundError(f"H5AD file not found: {path.resolve()}")

    if backed:
        console.print(
            f"[bold yellow]Loading AnnData in backed mode ('{backed}'):[/bold yellow] {path.name}"
        )
        return ad.read_h5ad(path, backed=backed)

    return ad.read_h5ad(path)


def save_h5ad(
    adata: ad.AnnData,
    output_path: Union[str, Path],
    compression: Optional[str] = "gzip",
) -> Path:
    """Save AnnData object to H5AD format with directory creation and compression."""
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    adata.write_h5ad(out, compression=compression)
    console.print(f"[bold green]✔ Saved AnnData to:[/bold green] {out}")
    return out


def export_for_seurat(
    adata: ad.AnnData,
    output_dir: Union[str, Path],
    layer: Optional[str] = "counts",
) -> None:
    """Export AnnData to CSV files compatible with R / Seurat CreateSeuratObject."""
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    if layer is not None and layer in adata.layers:
        X = adata.layers[layer]
    else:
        X = adata.X

    if sp.issparse(X):
        X = X.toarray()

    df_counts = pd.DataFrame(X.T, index=adata.var_names, columns=adata.obs_names)
    df_counts.to_csv(out_dir / "counts.csv")

    adata.obs.to_csv(out_dir / "metadata.csv")

    if "X_umap" in adata.obsm:
        df_umap = pd.DataFrame(
            adata.obsm["X_umap"], index=adata.obs_names, columns=["UMAP_1", "UMAP_2"]
        )
        df_umap.to_csv(out_dir / "embeddings.csv")

    console.print(f"[bold green]✔ Exported Seurat-compatible CSVs to:[/bold green] {out_dir}")
