"""
I/O and Data Ingestion Module for Single-Cell Analysis Workbench.
Provides lightweight wrappers for loading upstream matrices, 10x folders, H5AD files
with backed-mode support (NFR-3), and Seurat export.
Complies with scRNAseq_Workbench_Requirements.md (FR-6, NFR-3, NFR-5).
"""

from pathlib import Path
from typing import Optional, Union

import anndata as ad
import numpy as np
import pandas as pd
import scanpy as sc
import scipy.sparse as sp
from rich.console import Console

console = Console()


def load_upstream_matrix(
    file_path: Union[str, Path],
    transpose: bool = True,
    sparse: bool = True,
) -> ad.AnnData:
    """Load gene-by-cell count matrix generated by upstream pipelines (TSV/CSV).

    Parameters
    ----------
    file_path : str or Path
        Path to count matrix.
    transpose : bool, default True
        If True, transposes matrix from (Genes x Cells) to standard (Cells x Genes).
    sparse : bool, default True
        If True, stores count matrix as scipy CSR sparse matrix.

    Returns
    -------
    ad.AnnData
        AnnData object with counts in .X and raw counts in .layers['counts'].
    """
    path = Path(file_path)
    if not path.exists():
        raise FileNotFoundError(f"Count matrix file not found: {path.resolve()}")

    sep = "\t" if path.suffix in [".tsv", ".txt"] else ","
    console.print(f"[bold cyan]Ingesting upstream matrix:[/bold cyan] {path.name}")

    df = pd.read_csv(path, sep=sep, index_col=0)

    if transpose:
        X = df.values.T
        obs_names = [str(c) for c in df.columns]
        var_names = [str(r) for r in df.index]
    else:
        X = df.values
        obs_names = [str(r) for r in df.index]
        var_names = [str(c) for c in df.columns]

    if sparse:
        X = sp.csr_matrix(X, dtype=np.float32)
    else:
        X = np.asarray(X, dtype=np.float32)

    obs = pd.DataFrame(index=obs_names)
    var = pd.DataFrame(index=var_names)
    var["gene_name"] = var_names

    adata = ad.AnnData(X=X, obs=obs, var=var)
    adata.layers["counts"] = adata.X.copy()
    return adata


def load_10x_directory(dir_path: Union[str, Path]) -> ad.AnnData:
    """Load standard 10x Genomics folder (matrix.mtx.gz, barcodes.tsv.gz, features.tsv.gz)."""
    p = Path(dir_path)
    if not p.exists():
        raise FileNotFoundError(f"10x directory not found: {p.resolve()}")

    adata = sc.read_10x_mtx(p, var_names="gene_symbols", cache=False)
    adata.layers["counts"] = adata.X.copy()
    adata.var["gene_name"] = adata.var_names.astype(str)
    return adata


def load_h5ad(
    file_path: Union[str, Path],
    backed: Optional[str] = None,
) -> ad.AnnData:
    """Load AnnData from H5AD file, optionally in backed mode for large datasets (NFR-3).

    Parameters
    ----------
    file_path : str or Path
        Path to .h5ad file.
    backed : str, optional
        Mode for backed access (e.g. 'r' for read-only disk-backed mode).
        Use backed='r' when dataset size exceeds available RAM.

    Returns
    -------
    ad.AnnData
        Loaded AnnData object.
    """
    path = Path(file_path)
    if not path.exists():
        raise FileNotFoundError(f"H5AD file not found: {path.resolve()}")

    if backed:
        console.print(
            f"[bold yellow]Loading AnnData in backed mode ('{backed}'):[/bold yellow] {path.name}"
        )
        return ad.read_h5ad(path, backed=backed)

    return ad.read_h5ad(path)


def save_h5ad(
    adata: ad.AnnData,
    output_path: Union[str, Path],
    compression: str = "gzip",
) -> None:
    """Save AnnData object to compressed H5AD format with directory creation."""
    out_p = Path(output_path)
    out_p.parent.mkdir(parents=True, exist_ok=True)
    adata.write_h5ad(out_p, compression=compression)
    console.print(f"[bold green]✔ Saved AnnData to:[/bold green] {out_p}")


def export_for_seurat(
    adata: ad.AnnData,
    output_dir: Union[str, Path],
    layer: Optional[str] = "counts",
) -> None:
    """Export counts and metadata for seamless import into R / Seurat.

    Generates:
      - counts.csv (Genes x Cells)
      - metadata.csv (Cells x Annotations)
      - embeddings.csv (UMAP coordinates if present)
    """
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    if layer is not None and layer in adata.layers:
        X = adata.layers[layer]
    else:
        X = adata.X

    if sp.issparse(X):
        X = X.toarray()

    df_counts = pd.DataFrame(X.T, index=adata.var_names, columns=adata.obs_names)
    df_counts.to_csv(out_dir / "counts.csv")

    adata.obs.to_csv(out_dir / "metadata.csv")

    if "X_umap" in adata.obsm:
        df_umap = pd.DataFrame(
            adata.obsm["X_umap"], index=adata.obs_names, columns=["UMAP_1", "UMAP_2"]
        )
        df_umap.to_csv(out_dir / "embeddings.csv")

    console.print(f"[bold green]✔ Exported Seurat-compatible CSVs to:[/bold green] {out_dir}")
